# Generated by Django 5.0.7 on 2024-09-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_int', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_type_text', models.CharField(max_length=200)),
            ],
        ),
    ]
