# Generated by Django 5.0.7 on 2024-09-11 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name_text', models.CharField(max_length=200)),
                ('size_int', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('church_type_text', models.CharField(choices=[('BAPTIST', 'Baptist'), ('CATHOLIC', 'Catholic'), ('METHODIST', 'Methodist'), ('PRESBYTERIAN', 'Presbyterian'), ('NON_DENOMINATIONAL', 'Non-Denominational')], default='NON_DENOMINATIONAL', max_length=200)),
            ],
        ),
    ]
