# Generated by Django 5.0.7 on 2024-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='churches',
            field=models.ManyToManyField(related_name='users', to='churches.church'),
        ),
    ]
