# Generated by Django 5.0.7 on 2024-10-08 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_users_churches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name_text', models.CharField(max_length=200)),
                ('size_int', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('churches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='churches.church')),
            ],
        ),
    ]
